# Generated by Django 2.1.2 on 2018-12-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Second_App', '0002_auto_20181211_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
    ]
